language: rust
rust:
  - stable
  - beta

os:
  - linux
  - osx

matrix:
  allow_failures:
    - rust: beta

sudo: false
cache:
  - cargo
  - pip
before_script:
  - pip install --user PySocks
  - export PATH=$HOME/.local/bin:~/.cargo/bin:$PATH
  - (cargo install rustfmt || true)
script:
  - cargo fmt -- --write-mode=diff
  - cargo test --test encrypt
  - cargo test asyncdns
  - ./run.sh s -d start --log-file ssserver.log --pid-file ssserver.pid
  - ./run.sh c -d start --log-file sslocal.log --pid-file sslocal.pid
  - sleep 1
  - ./tests/test_tcp.py
  - ./tests/test_udp.py

notifications:
  email:
    on_success: never
