language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

matrix:
  allow_failures:
    - rust: beta
    - rust: nightly

sudo: false
cache:
  - cargo
  - pip
before_script:
  - pip install --user nose PySocks shadowsocks
  - export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$HOME/Library/Python/2.7/bin/:$PATH
  - (cargo install rustfmt || true)
script:
  - cargo fmt -- --write-mode=diff
  - cargo test
  - bash tests/test.sh
after_failure:
  - echo "======== sslocal logging ========" && cat /tmp/ssc.log
  - echo "======== ssserver logging ========" && cat /tmp/sss.log

notifications:
  email:
    on_success: change
