language: rust

rust:
  - stable
  - beta
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - cargo build
  - cargo build --features sslocal
notifications:
  email:
    on_success: never
os:
  - linux
  - osx
