language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

matrix:
  allow_failures:
    - rust: beta
    - rust: nightly

sudo: false
cache:
  - cargo
  - pip
before_script:
  - pip install --user nose PySocks
  - export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$HOME/Library/Python/2.7/bin/:$PATH
  - (cargo install rustfmt || true)
script:
  - cargo fmt -- --write-mode=diff
  - cargo test
  - ./run.sh s -d start --log-file ssserver.log --pid-file ssserver.pid
  - ./run.sh c -d start --log-file sslocal.log --pid-file sslocal.pid
  - python tests/echo_server.py &
  - nosetests tests/test_tcp.py
  - nosetests tests/test_udp.py

notifications:
  email:
    on_success: never
