build: false

environment:
  PYTHON: "C:\\Python27"
  PYTHON_VERSION: "2.7.12"
  PYTHON_ARCH: "32"

  matrix:
    - TARGET: x86_64-pc-windows-msvc

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin;%PYTHON%/Scripts/
  - rustc -V
  - cargo -V
  - "pip.exe install nose PySocks"

test_script:
  - cargo test --test encrypt
  - cargo test asyncdns
  - cargo run -- -h
  - ps: Start-Process cargo run -- -c tests\config\server_conf.toml --log-file ssserver.log
  - cargo run --features sslocal -- -h
  - ps: Start-Process cargo run --features sslocal -- -c tests\config\client_conf.toml --log-file sslocal.log
  - ps: Start-Process python tests\echo_server.py
  - nosetests tests\test_tcp.py
  - nosetests tests\test_udp.py
