[package]
name = "shadowsocks-rust"
version = "0.1.0"
authors = ["loggerhead <lloggerhead@gmail.com>"]
readme = "README.md"
license = "MIT"

[lib]
name = "shadowsocks"

[dependencies]
mio = "0.5"
log = "0.3"
fnv = "1"
rand = "0.3"
toml = "0.1"
regex = "0.1"
try_opt = "*"
byteorder = "0.5"
lru-cache = "0.0.7"
env_logger = "0.3"
lazy_static = "0.2"
rust-crypto = "0.2"
